name: Build macOS wheels (PR merge to main)

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  wheel:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out merge commit
        uses: actions/checkout@v4
        with:
          # Build the exact merge commit that landed on main
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install cmake libxml2 minizip-ng zlib-ng pybind11

      - name: Install Python build dependencies
        run: |
          python -m pip install -U pip build scikit-build-core pybind11

      - name: Build wheel
        working-directory: python
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CMAKE_BUILD_PARALLEL_LEVEL: "4"
        run: |
          python -m build -w --config-setting=cmake.define.CMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: turboxl-macos-${{ matrix.arch }}-wheel
          path: python/dist/*.whl
