name: Build macOS wheels (PR merge to main)

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  wheel:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install cmake libxml2 minizip-ng zlib-ng pybind11

      - name: Install Python build dependencies
        run: |
          python -m pip install -U pip build scikit-build-core pybind11

      - name: Build wheel
        env:
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CMAKE_BUILD_PARALLEL_LEVEL: "4"
        run: |
          python -m build -w --config-setting=cmake.define.CMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.arch }}
          path: dist/*.whl

  publish:
    needs: wheel
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  release-assets:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: v0.1.12
          name: v0.1.12
          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
